12 glosary filter
PlasmaStorm7/GMTK-Game-Jam-2024-project pull request #30
Opened 2024-08-17 20:44 UTC by Radu-Florian-Sava

2024-08-17 21:06 UTC, PlasmaStorm7 requested changes
vezi DLL-urile ce fac/nu fac

2024-08-17 21:06 UTC, PlasmaStorm7 commented on Scenes/Glossary/Glo318.tmp
temp file, yeet

2024-08-17 21:06 UTC, PlasmaStorm7 commented on Scenes/Glossary/Glossary_element.tscn
asta face ceva?

2024-08-17 21:06 UTC, PlasmaStorm7 commented on addons/godot-git-plugin/win64/~libgit_plugin.windows.editor.x86_64.dll
de ce ai sters un DLL? :))

2024-08-17 21:06 UTC, PlasmaStorm7 commented on addons/godot-jolt/windows/~godot-jolt_windows-x64_editor.dll
sus DLL deleted

2024-08-18 09:31 UTC, Radu-Florian-Sava commented on Scenes/Glossary/Glossary_element.tscn
inlocuieste mock-ul pe care il foloseam, avem pentru elementele din lista glosarului

2024-08-18 10:02 UTC, PlasmaStorm7 approved these changes

2024-08-18 10:02 UTC, merged